Assignment3/config/routes.rb
Wiki::Application.routes.draw do

resources :items

match '/list', :to => 'items#list'

match '/show', :to => 'items#show'

match '/add', :to => 'items#addItem'

resources :users

match '/secret', :to => 'pages#secret'

match '/konami', :to => 'pages#konami'

match '/signup',  :to => 'users#new'

match '/home', :to => 'pages#home'

match '/description', :to => 'pages#description'

match '/stream', :to => 'pages#stream'

match '/sources', :to => 'pages#sources'

match '/contact', :to => 'pages#contact'

match '/new', :to => 'users#new'

match '/show', :to => 'users#show'

match '/new_item', :to => 'items#addItem'

root :to => 'items#list'

end

Assignment3/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
  				   :length   => { :maximum => 50 }

  validates :email, :presence => true,
  					:format   => { :with => email_regex },
  					:uniqueness => { :case_sensitive => false }

validates :password, :presence     => true,
                     :confirmation => true,
                     :length       => { :within => 6..40 }


before_save :encrypt_password

def has_password?(password_submit)
    encrypted_password == encrypt(password_submit)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

Assignment3/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Assignment3/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_filter :setListHeader, :setListFooter

  def setListHeader
    @listHeader = { "Home" => home_path, "Description" => description_path,
                    "Stream" => stream_path, "Konami Code" => konami_path }
  end

  def setListFooter
    @listFooter = { "Sources" => sources_path, "Contact" => contact_path,
                    "Capcom" => 'http://www.capcom.com/', "Hadouken !" => 'http://en.wikipedia.org/wiki/Hadouken_(Street_Fighter)#Hadouken' }
  end

  def home
  	@title = "Home"
  end

  def description
  	@title = "Description"
  end

  def stream
  	@title = "Stream"
  end

  def contact
  	@title = "Contact"
  end

  def sources
  	@title = "Sources"
  end

  def konami
    @title = "Konami"
  end

  def secret
    @title = "Secret"
  end

end

Assignment3/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :setListHeader, :setListFooter

  def setListHeader
    @listHeader = { "Home" => home_path, "Description" => description_path,
                    "Stream" => stream_path, "Konami Code" => konami_path }
  end

  def setListFooter
    @listFooter = { "Sources" => sources_path, "Contact" => contact_path,
                    "Capcom" => 'http://www.capcom.com/', "Hadouken !" => 'http://en.wikipedia.org/wiki/Hadouken_(Street_Fighter)#Hadouken' }
  end

  def new
  	@title = "Sign Up"
    @user = User.new
  end

 def show
    @user = User.find(params[:id])
    @title = @user.name
  end	
end

Assignment3/app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "MyLittleWiki"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

Assignment3/app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <% nbPipe = @listFooter.size %>
      <% @listFooter.each do |key, value| %>
      <li><%= link_to key, value %> <% if nbPipe > 1 %> <%= "|" %> <% end %> </li>
      <% nbPipe -= 1 %>
      <% end %>

    </ul>
  </nav>
</footer>

Assignment3/app/views/layouts/_header.html.erb
<header>

<script type="text/javascript" src="https://raw.github.com/snaptortoise/konami-js/master/konami.js"></script>
<script type="text/javascript">

	var konami = new Konami("<%= secret_url %> ");
	
</script>


    <% logo = image_tag("logo_panier.png", :alt => "Panier Logo", :class => "round") %>
	<%= link_to logo, root_path %>

  

    <nav class="round left">

    <ul>
      <li> <%= link_to "Add A New Product", add_path %></li>
    </ul>
    </nav>

<!-- Remove Nav header to put it on the left of section tag -->
    <nav class="round">

    <ul>
      <li> <%= link_to "List All Products", list_path %></li>


      </ul>
    </nav>

</header>

Assignment3/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= title %></title>
      <%= render 'layouts/stylesheets' %>
	 <%= csrf_meta_tags %>
</head>

<body>
<!-- Header apart of the main div on the left
<div class="container">
    <%= render 'layouts/header' %>

  <section class="round">
        <% flash.each do |key, value| %>
          <div class="flash <%= key %>"><%= value %></div>
        <% end %>
        <%= yield %>
  </section>

  <!-- <%= render 'layouts/footer' %> -->


</div>


</body>

</html>

Assignment3/app/views/pages/home.html.erb
<h1>Home</h1>
    <p>
      Welcome on the little wiki of StreetFighter. </br>
      If you want to know what is Street Fighter, follow this link:
      <%= link_to "What is Street Fighter ?", description_path, :class => "description_button round" %> </br>
      And if you want to know about a great player:
      <%= link_to "Daigo Umehara", stream_path, :class => "stream_button round" %>
    </p>
<!--     <%= link_to "Resgister you, fast !", signup_path, :class => "signup_button round" %>
 -->

Assignment3/app/views/shared/_error_messages.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "errors") %> 
        prevented to save your registration</h2>
    <p>Thanks to fix those parts :</p>
    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Assignment3/app/views/users/new.html.erb
<h1>Sign up </h1>
	<%= form_for(@user) do |f| %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
	<% end %>