Wiki_part1/config/routes.rb
Wiki::Application.routes.draw do

  get "users/new"

  match '/signup',  :to => 'users#new'

match '/home', :to => 'pages#home'

match '/description', :to => 'pages#description'

match '/stream', :to => 'pages#stream'

match '/sources', :to => 'pages#sources'

match '/contact', :to => 'pages#contact'

root :to => 'pages#home'

end

Wiki_part1/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  	@titre = "Home"
  end

  def description
  	@titre = "Description"
  end

  def stream
  	@titre = "Stream"
  end

  def contact
  	@title=  "Contact"
  end

  def sources
  	@title = "Sources"
  end
end

Wiki_part1/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@titre = "Inscription"
  end
end

Wiki_part1/app/helpers/application_helper.rb
module ApplicationHelper
  def titre
    base_titre = "MyLittleWiki"
    if @titre.nil?
      base_titre
    else
      "#{base_titre} | #{@titre}"
    end
  end

end

Wiki_part1/app/views/layouts/_header.html.erb
<header>
    <% logo = image_tag("Street_Fighter_IV_Logo.png", :alt => "Street Fighter 4", :class => "round") %>
	<%= link_to logo, root_path %>
    <nav class="round">
      <ul>
        <li><%= link_to "Home", home_path %></li>
        <li><%= link_to "Description", description_path %></li>
        <li><%= link_to "Stream", stream_path %></li>
      </ul>
    </nav>
</header>

Wiki_part1/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title><%= titre %></title>
      <%= render 'layouts/stylesheets' %>
	 <%= csrf_meta_tags %>
</head>

<body>
<div class="container">
    <%= render 'layouts/header' %>

  <section class="round">
    <%= yield %>
  </section>
  <%= render 'layouts/footer' %>
</div>
</body>

</html>