Assignment4/config/routes.rb
Wiki::Application.routes.draw do

resources :users
resources :sessions, :only => [:new, :create, :destroy]
resources :microposts

match '/secret', :to => 'pages#secret'

match '/konami', :to => 'pages#konami'

match '/signup',  :to => 'users#new'

match '/home', :to => 'pages#home'

match '/description', :to => 'pages#description'

match '/stream', :to => 'pages#stream'

match '/sources', :to => 'pages#sources'

match '/contact', :to => 'pages#contact'

match '/new', :to => 'users#new'

match '/show', :to => 'users#show'

match '/new_item', :to => 'items#addItem'

match '/signin',  :to => 'sessions#new'

match '/signout', :to => 'sessions#destroy'

match '/addPost', :to => 'microposts#new'

match '/showPost', :to => 'microposts#show'

match '/archive', :to => 'microposts#store'

root :to => 'microposts#show'

end

Assignment4/app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :description, :price, :productName, :urlImage

  validates :productName, :presence => true,
  			:length => { :maximum => 50 }

  validates :urlImage, :description, :presence => true

  validates :price, :presence => true, 
  			:numericality => { :greater_than_or_equal_to => 0 }

end

Assignment4/app/models/micropost.rb
class Micropost < ActiveRecord::Base
  attr_accessible :content, :tags, :title

  post_regex = /\A[\w\d]+([,][\s]*[\w\d]+)*\z/i

  validates :title, :presence => true, :length => { :maximum => 75}
  validates :content, :presence => true
  validates :tags, :format => { :with => post_regex }

end

Assignment4/app/models/user.rb
class User < ActiveRecord::Base

  attr_accessor :password
  attr_accessible :name, :email, :password, :password_confirmation

  email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :name, :presence => true,
  				   :length   => { :maximum => 50 }

  validates :email, :presence => true,
  					:format   => { :with => email_regex },
  					:uniqueness => { :case_sensitive => false }

validates :password, :presence     => true,
                     :confirmation => true,
                     :length       => { :within => 6..40 }


before_save :encrypt_password

def has_password?(password_submit)
    encrypted_password == encrypt(password_submit)
  end

  def self.authenticate(email, submitted_password)
    user = find_by_email(email)
    return nil  if user.nil?
    return user if user.has_password?(submitted_password)
  end

  def self.authenticate_with_salt(id, cookie_salt)
    user = find_by_id(id)
    (user && user.salt == cookie_salt) ? user : nil
  end

  private

    def encrypt_password
      self.salt = make_salt if new_record?
      self.encrypted_password = encrypt(password)
    end

    def encrypt(string)
      secure_hash("#{salt}--#{string}")
    end

    def make_salt
      secure_hash("#{Time.now.utc}--#{password}")
    end

    def secure_hash(string)
      Digest::SHA2.hexdigest(string)
    end

end

Assignment4/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  include SessionsHelper

  before_filter do 
  	@listHeader = { "Home" => showPost_path, "Profil" => current_user, "Description" => description_path, "Archive" => archive_path
                  }

    @listFooter = { "Stream" => stream_path,  "Konami Code" => konami_path, "Sources" => sources_path, "Contact" => contact_path,
                    "Capcom" => 'http://www.capcom.com/', "Hadouken !" => 'http://en.wikipedia.org/wiki/Hadouken_(Street_Fighter)#Hadouken' }
  end
end

Assignment4/app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_filter :setListHeader, :setListFooter

  def setListHeader
    @listHeader = { "Home" => home_path, "Description" => description_path,
                    "Stream" => stream_path, "Konami Code" => konami_path }
  end

  def setListFooter
    @listFooter = { "Sources" => sources_path, "Contact" => contact_path,
                    "Capcom" => 'http://www.capcom.com/', "Hadouken !" => 'http://en.wikipedia.org/wiki/Hadouken_(Street_Fighter)#Hadouken' }
  end

  def list
  	@title = "List"
    @allItem = Item.all
  end

  def show
    @item = Item.find(params[:id])
    @title = @item.productName
  end

  def addItem
  	@item = Item.new
  	@title = "New Item"
  end

  def create
    @item = Item.new(params[:item])
    if @item.save

      # If we want to warn the user
      # flash[:success] = "Item added !"

      redirect_to @item
    else
      @title = "New Item"
      render :action =>'addItem'
    end
  end
end

Assignment4/app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController

  def new
  	@title = "Add a micropost"
  	@micro = Micropost.new
  end

  def show
  	@title = "All microposts"
  	@micro = Micropost.all
  end

  def store
  	@title = "Lists of store microposts"
    @micro = Micropost.all
  end

  def create
  	@micro = Micropost.new(params[:micropost])
  	if @micro.save
  		flash[:success] = "Post Added !"
  		redirect_to root_path
  	else
  		@title = "Add a micropost"
  		render 'new'
  	end
  end


end

Assignment4/app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  	@title = "Home"
  end

  def description
  	@title = "Description"
  end

  def stream
  	@title = "Stream"
  end

  def contact
  	@title = "Contact"
  end

  def sources
  	@title = "Sources"
  end

  def konami
    @title = "Konami"
  end

  def secret
    @title = "Secret"
  end

end

Assignment4/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  	@title = "Sign In"
  end

  def create
  	user = User.authenticate(params[:session][:email],
                             params[:session][:password])
    if user.nil?
      flash.now[:error] = "Invalid Password/Email."
      @title = "Sign In"
      render 'new'
    else
	  sign_in user
      redirect_to user
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

end

Assignment4/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@title = "Sign Up"
    @user = User.new
  end

 def show
    @user = User.find(params[:id])
    @title = @user.name
  end	

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome #{@user.name} !"
      redirect_to @user
    else
      @title = "Sign Up"
      render 'new'
    end
  end

end

Assignment4/app/helpers/application_helper.rb
module ApplicationHelper

  def logo
    image_tag("Street_Fighter_IV_Logo.png", :alt => "Street Fighter 4", :class => "round")
  end

  def title
    base_title = "MyLittleWiki"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

Assignment4/app/helpers/items_helper.rb
module ItemsHelper
end

Assignment4/app/helpers/microposts_helper.rb
module MicropostsHelper
end

Assignment4/app/helpers/pages_helper.rb
module PagesHelper
end

Assignment4/app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    cookies.permanent.signed[:remember_token] = [user.id, user.salt]
    self.current_user = user
  end

  def sign_out
    cookies.delete(:remember_token)
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= user_from_remember_token
  end

  def signed_in?
    !current_user.nil?
  end

  private

    def user_from_remember_token
      User.authenticate_with_salt(*remember_token)
    end

    def remember_token
      cookies.signed[:remember_token] || [nil, nil]
    end

end

Assignment4/app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { :size => 50 })
    gravatar_image_tag(user.email.downcase, :alt => user.name,
                                            :class => 'gravatar',
                                            :gravatar => options)
  end
end

Assignment4/app/views/items/addItem.html.erb
<h1>Add A New Item</h1>
	<%= form_for(@item) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label "Product Name" %><br />
		<%= f.text_field :productName %>
	</div>
	<div class="field">
		<%= f.label "Price" %><br />
		<%= f.text_field :price %>
	</div>
	<div class="field">
		<%= f.label "Url Image" %><br />
		<%= f.text_field :urlImage %>
	</div>
	<div class="field">
		<%= f.label "Description" %><br />
		<%= f.text_field :description %>
	</div>
	<div class="actions">
		<%= f.submit "New Item" %>
	</div>
	<% end %>

Assignment4/app/views/items/list.html.erb
<h1>All The Products</h1>

<ul>
<% if @allItem.count == 0 %>
	</br>
	<p class="center"> Sorry, but you don't have any product ! </p>
<% else %>
<% @allItem.each do |a| %>
	<li>
		<%= link_to a.productName, a %>
	</li>	
<% end %>

<% end %>
</ul>

Assignment4/app/views/items/show.html.erb
<table>
<tr>
	<td align="left">
	<%= image_tag(@item.urlImage, :size => "300x300") %>
	</td>
<td style="text-align:right;vertical-align:top">
 <strong> 
 	<font size="10pt">
 	<%= @item.productName %> 
	 </font>
</br>
</br>
</br>
 	<font size="6pt">
		<%= @item.price %>
	</font>
 </strong>
</td>
</tr>
</table>

<p> <center> <%= @item.description %> </center> </p>

Assignment4/app/views/microposts/new.html.erb
<h1>Add a micropost</h1>
	<%= form_for(@micro) do |f| %>
	<%= render 'shared/error_messages_post' %>
	<div class="field">
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</div>
	<div class="field">
		<%= f.label :content %><br />
		<%= f.text_area :content, :size => "20x30"%>
	</div>
	<div class="field">
		<%= f.label :tags %><br />
		<%= f.text_field :tags %>
	</div>
	<div class="actions">
		<%= f.submit "Add a micropost" %>
	</div>
	<% end %>

Assignment4/app/views/microposts/show.html.erb
<% if @micro.length == 0 %>
<h1><%= "No Posts" %></h1>
<% end %>

<% @micro.reverse.each do |m| %>
	<table class="profile">
		<tr>
			<td id="<%= m.title %>" ><h1><%= m.title %></h1></td>
		</tr>
		<tr>
			<td><%= m.content %></td>
		</tr>
		<tr>
			<td><U>Tags</U> --> <%= m.tags %></td>		
		</tr>
	</table>
</br> </br>
<% end %>

Assignment4/app/views/microposts/store.html.erb
<h1> Archive Post </h1>
<ul>
<% @micro.reverse.each do |m| %>
	<li>
		<%= link_to m.title,  url_for(:action => 'show', :anchor => m.title) %>
	</li>
<% end %>
</ul>

Assignment4/app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>
To contact me: "benoit.mira@gmail.com"
</br>
To defy me via XBOX LIVE: "TSR Miraboule"
</p>

Assignment4/app/views/pages/description.html.erb
<h1>Description</h1>
    <p>
     Street Fighter commonly abbreviated as SF, is a series of fighting games developed in Japan. The game's playable characters originate from around the world, each with his or her own unique fighting style.
Since Capcom released the first arcade game in August 1987, the series has had total home software sales of 33 million units, and arcade cabinet sales of over 500,000 units generating more than $1 billion in revenue, qualifying it for the list of best-selling video game franchises. The best-selling game in the series, Street Fighter II, exceeded $1.5 billion in revenue. The franchise has enjoyed significant success all around the world.
    </p>

Assignment4/app/views/pages/home.html.erb
<h1>Home</h1>
    <p>
      Welcome on the little wiki of StreetFighter. </br>
      If you want to know what is Street Fighter, follow this link:
      <%= link_to "What is Street Fighter ?", description_path, :class => "description_button round" %> </br>
      And if you want to know about a great player:
      <%= link_to "Daigo Umehara", stream_path, :class => "stream_button round" %>
    </p>
    <%= link_to "Resgister you, fast !", signup_path, :class => "signup_button round" %>

Assignment4/app/views/pages/konami.html.erb
<h1>Konami</h1>
    <p>
      The Konami Code was created by Kazuhisa Hashimoto, who was developing the home port of the 1985 arcade game Gradius, a scrolling shooter released on the NES in 1986. Finding the game too difficult to play through during testing, he created a cheat code to give the player a full set of power-ups (normally attained gradually throughout the game).
    </p>

    <p>
    	Some games uses this Konami code like:
    	<li>- Contra</li>
    	<li>- Silent Hill 3</li>
    	<li>- Assassin's Creed III</li>
    	<li>- Borderlands 2</li>
    	<li>- Mortal Kombat 3</li>
    </br>
    	And, maybe this website ... 
    </p>

Assignment4/app/views/pages/secret.html.erb
<h1>Secret</h1>
    <p>
      You found my secret place.
  </br>
  Now I am going to tell you the <%= link_to "secret of Life", "http://en.wikipedia.org/wiki/Answer_to_The_Ultimate_Question_of_Life,_the_Universe,_and_Everything#Answer_to_the_Ultimate_Question_of_Life.2C_the_Universe.2C_and_Everything_.2842.29" %>.
    </p>

Assignment4/app/views/pages/sources.html.erb
<h1>Sources</h1>
<p>Here the lists of the sources for this website:
	<ul>
		<li>- Description and History of Street Fighter : <%= link_to "Wikipedia", "http://en.wikipedia.org/wiki/Street_Fighter" %></li>
		<li>- Hadouken Image: <%= link_to "HADOUKEN", "https://www.google.com/search?q=hoadouken&rlz=1C1CHFX_frFR467FR468&aq=f&um=1&ie=UTF-8&hl=fr&tbm=isch&source=og&sa=N&tab=wi&ei=xCU2UfXBM5C7hAf8yYCIDg&biw=1680&bih=925&sei=5iU2Uf7YHYOQhQeQ04GwDA#um=1&hl=fr&safe=off&rlz=1C1CHFX_frFR467FR468&tbm=isch&sa=1&q=hadouken+street+fighter&oq=hadouken+street+fighter&gs_l=img.3..0j0i24l2.1468.3325.1.3397.16.4.0.12.12.0.64.158.4.4.0...0.0...1c.1.5.img.xGC-XewynWc&bav=on.2,or.r_gc.r_pw.r_cp.r_qf.&bvm=bv.43148975,d.ZG4&fp=f8fa3a0f84acf6a0&biw=1680&bih=925&imgrc=5_1JBVBnwi09sM%3A%3BhIMa3LWbQGVqoM%3Bhttp%253A%252F%252Fimages1.wikia.nocookie.net%252F__cb20110908180746%252Fmarvelvscapcom%252Fimages%252F1%252F1e%252FRyu-hadoken-artwork.png%3Bhttp%253A%252F%252Fmarvelvscapcom.wikia.com%252Fwiki%252FHadoken%3B574%3B411" %></li>
		<li>- Daigo Umehara: <%= link_to "Carreer and life", "http://fr.wikipedia.org/wiki/Daigo_Umehara" %></li>
	</ul>
</p>

Assignment4/app/views/pages/stream.html.erb
<h1>Stream</h1>
	<p>
	 Daigo Umehara , born 19 May 1981, is a Japanese arcade fighting video game player. He specializes in 2D arcade fighting games, mainly those released by Capcom. Known as "Daigo" or "The Beast" in the West and "Umehara" or "Ume" in Japan, Umehara is one of the world's most famous Street Fighter players and is often considered its greatest, as well. He currently holds a world record of "the most successful player in major tournaments of Street Fighter" in Guinness World Records. </br></br>
	 He was really famous during his match in the losers bracket final in Evolution Championship Series 2004's thanks of this video: </br>
	 <iframe width="600" height="360" src="http://www.youtube.com/embed/v7cW2nMf1gk" frameborder="0" allowfullscreen></iframe> </br></br>
	 There are some stream of Street Fighter on Twitch: <%= link_to "Super Street Fighter 4", "http://fr.twitch.tv/directory/game/Super%20Street%20Fighter%20IV" %>
    </p>

Assignment4/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "errors") %> 
        prevented to save your registration</h2>
    <p>Thanks to fix those parts :</p>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Assignment4/app/views/shared/_error_messages_post.html.erb
<% if @micro.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@micro.errors.count, "errors") %>
        prevented to save your post</h2>
    <p>Thanks to fix those parts :</p>
    <ul>
    <% @micro.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

Assignment4/app/views/users/new.html.erb
<h1>Sign up </h1>
	<%= form_for(@user) do |f| %>
	<%= render 'shared/error_messages' %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>
	<div class="field">
		<%= f.label :password_confirmation, "Confirmation" %><br />
		<%= f.password_field :password_confirmation %>
	</div>
	<div class="actions">
		<%= f.submit "Sign up" %>
	</div>
	<% end %>

Assignment4/app/views/users/show.html.erb
<table class="profile" summary="Information profil">
  <tr>
    <td class="main">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.name %><br />
      <strong>URL</strong>  <%= link_to user_path(@user), @user %>
    </td>
  </tr>
</table>